### ISSUE TITLE
Properties panel - UNSYNCED LYRICS bug

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#313] opened 2020-05-04 21:54 UTC
See here in the properties panel.

Notice the weird overlapping on the unsynced lyrics value.

![image](https://user-images.githubusercontent.com/14054664/80962536-20883700-8e05-11ea-9f95-c8c204b02c28.png)

The Unsynced Lyric tags contains.
```
Release type:		Release
----------------------------------------------
Exclusive to beatport:	No
----------------------------------------------
RDNK does not have a nationality or race; its not even a human, because it does not possess a body yet. It is an astral force of the universe. On its way to Earth RDNK has been creating music in order to communicate with humans in a universal language. To make this music palpable for humans, RDNK took the best fitting parts from their past music and included them into a new sound. The outcome can be called Future Techno.
----------------------------------------------
Tagged by:		Mp3Tag w/ beatport.com scripts [v4.4 by stevehero™] (◣_◢) (http://bit.ly/2EmyidV)
```

**Comment by reupen** [comment] 2020-08-27 18:53
This was caused by the tab characters inadvertently activating an old feature that used tab characters for alignment and pseudo-columns (which, allows overlapping text in some cases).

This will be fixed in version 1.5.0 by disabling that feature in Item properties. Tab characters, however, will render as zero-width as they often do in foobar2000.

**Closed by reupen** 2020-08-27 18:53 UTC
Labels: bug
